#include "sys/aivm_syscall_contracts.h"

#include <string.h>

static const AivmSyscallContract Contracts[] = {
    { 5U, "sys.net.tcp.close", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 6U, "sys.console.write", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_CONSOLE },
    { 7U, "sys.console.writeLine", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_CONSOLE },
    { 8U, "sys.console.readLine", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING, AIVM_SYSCALL_CAPABILITY_CONSOLE },
    { 9U, "sys.console.readAllStdin", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING, AIVM_SYSCALL_CAPABILITY_CONSOLE },
    { 10U, "sys.console.writeErrLine", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_CONSOLE },
    { 16U, "sys.stdout.writeLine", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_CONSOLE },
    { 11U, "sys.process.cwd", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING, AIVM_SYSCALL_CAPABILITY_PROCESS },
    { 12U, "sys.process.env.get", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING, AIVM_SYSCALL_CAPABILITY_PROCESS },
    { 18U, "sys.process.args", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_NODE, AIVM_SYSCALL_CAPABILITY_PROCESS },
    { 105U, "sys.process.spawn", 4U, { AIVM_VAL_STRING, AIVM_VAL_NODE, AIVM_VAL_STRING, AIVM_VAL_NODE, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_PROCESS },
    { 106U, "sys.process.wait", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_PROCESS },
    { 107U, "sys.process.kill", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL, AIVM_SYSCALL_CAPABILITY_PROCESS },
    { 108U, "sys.process.stdout.read", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BYTES, AIVM_SYSCALL_CAPABILITY_PROCESS },
    { 109U, "sys.process.stderr.read", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BYTES, AIVM_SYSCALL_CAPABILITY_PROCESS },
    { 110U, "sys.process.poll", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_PROCESS },
    { 117U, "sys.remote.call", 3U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_REMOTE },
    { 120U, "sys.host.openDefault", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL, AIVM_SYSCALL_CAPABILITY_HOST },
    { 121U, "sys.image.decodeToRgbaBase64", 2U, { AIVM_VAL_BYTES, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING, AIVM_SYSCALL_CAPABILITY_IMAGE },
    { 28U, "sys.platform", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING, AIVM_SYSCALL_CAPABILITY_PLATFORM },
    { 29U, "sys.arch", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING, AIVM_SYSCALL_CAPABILITY_PLATFORM },
    { 30U, "sys.os.version", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING, AIVM_SYSCALL_CAPABILITY_PLATFORM },
    { 31U, "sys.runtime", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING, AIVM_SYSCALL_CAPABILITY_PLATFORM },
    { 13U, "sys.time.nowUnixMs", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_TIME },
    { 14U, "sys.time.monotonicMs", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_TIME },
    { 15U, "sys.time.sleepMs", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_TIME },
    { 122U, "sys.time.timeZoneId", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING, AIVM_SYSCALL_CAPABILITY_TIME },
    { 123U, "sys.time.timeZoneOffsetMinutesAt", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_TIME },
    { 17U, "sys.process.exit", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_PROCESS },
    { 19U, "sys.fs.file.read", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BYTES, AIVM_SYSCALL_CAPABILITY_FILESYSTEM },
    { 20U, "sys.fs.file.exists", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL, AIVM_SYSCALL_CAPABILITY_FILESYSTEM },
    { 21U, "sys.fs.dir.list", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_NODE, AIVM_SYSCALL_CAPABILITY_FILESYSTEM },
    { 22U, "sys.fs.path.stat", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_NODE, AIVM_SYSCALL_CAPABILITY_FILESYSTEM },
    { 23U, "sys.fs.path.exists", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL, AIVM_SYSCALL_CAPABILITY_FILESYSTEM },
    { 24U, "sys.fs.file.write", 2U, { AIVM_VAL_STRING, AIVM_VAL_BYTES, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_FILESYSTEM },
    { 25U, "sys.fs.dir.create", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_FILESYSTEM },
    { 103U, "sys.fs.file.delete", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL, AIVM_SYSCALL_CAPABILITY_FILESYSTEM },
    { 104U, "sys.fs.dir.delete", 2U, { AIVM_VAL_STRING, AIVM_VAL_BOOL, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL, AIVM_SYSCALL_CAPABILITY_FILESYSTEM },
    { 124U, "sys.fs.file.openRead", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_FILESYSTEM },
    { 125U, "sys.fs.file.readChunk", 2U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BYTES, AIVM_SYSCALL_CAPABILITY_FILESYSTEM },
    { 126U, "sys.fs.file.close", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL, AIVM_SYSCALL_CAPABILITY_FILESYSTEM },
    { 127U, "sys.fs.file.openWrite", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_FILESYSTEM },
    { 128U, "sys.fs.file.writeChunk", 2U, { AIVM_VAL_INT, AIVM_VAL_BYTES, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_FILESYSTEM },
    { 37U, "sys.crypto.base64Encode", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING, AIVM_SYSCALL_CAPABILITY_CRYPTO },
    { 38U, "sys.crypto.base64Decode", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING, AIVM_SYSCALL_CAPABILITY_CRYPTO },
    { 39U, "sys.crypto.sha1", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING, AIVM_SYSCALL_CAPABILITY_CRYPTO },
    { 40U, "sys.crypto.sha256", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING, AIVM_SYSCALL_CAPABILITY_CRYPTO },
    { 41U, "sys.crypto.hmacSha256", 2U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING, AIVM_SYSCALL_CAPABILITY_CRYPTO },
    { 42U, "sys.crypto.randomBytes", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BYTES, AIVM_SYSCALL_CAPABILITY_CRYPTO },
    { 27U, "sys.net.tcp.connect", 2U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 32U, "sys.net.tcp.listen", 2U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 33U, "sys.net.tcp.listenTls", 4U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 34U, "sys.net.tcp.accept", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 35U, "sys.net.tcp.read", 2U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BYTES, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 36U, "sys.net.tcp.write", 2U, { AIVM_VAL_INT, AIVM_VAL_BYTES, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 61U, "sys.net.tcp.connectTls", 2U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 62U, "sys.net.tcp.connectStart", 2U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 63U, "sys.net.tcp.connectTlsStart", 2U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 64U, "sys.net.tcp.readStart", 2U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 65U, "sys.net.tcp.writeStart", 2U, { AIVM_VAL_INT, AIVM_VAL_BYTES, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 66U, "sys.net.async.poll", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 67U, "sys.net.async.await", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 68U, "sys.net.async.cancel", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 69U, "sys.net.async.resultInt", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 70U, "sys.net.async.resultBytes", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BYTES, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 71U, "sys.net.async.error", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 43U, "sys.net.udp.bind", 2U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 44U, "sys.net.udp.recv", 2U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_NODE, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 45U, "sys.net.udp.send", 4U, { AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_BYTES, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_NETWORK },
    { 46U, "sys.ui.createWindow", 3U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_UI },
    { 47U, "sys.ui.beginFrame", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_UI },
    { 48U, "sys.ui.drawRect", 6U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_UI },
    { 49U, "sys.ui.drawText", 6U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_UI },
    { 50U, "sys.ui.endFrame", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_UI },
    { 51U, "sys.ui.pollEvent", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_NODE, AIVM_SYSCALL_CAPABILITY_UI },
    { 52U, "sys.ui.present", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_UI },
    { 53U, "sys.ui.closeWindow", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_UI },
    { 54U, "sys.ui.drawLine", 7U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_UI },
    { 55U, "sys.ui.drawEllipse", 6U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_UI },
    { 56U, "sys.ui.drawPath", 4U, { AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_UI },
    { 57U, "sys.ui.drawImage", 6U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_UI },
    { 58U, "sys.ui.getWindowSize", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_NODE, AIVM_SYSCALL_CAPABILITY_UI },
    { 72U, "sys.ui.waitFrame", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_UI },
    { 73U, "sys.worker.start", 2U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_WORKER },
    { 74U, "sys.worker.poll", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_WORKER },
    { 75U, "sys.worker.result", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING, AIVM_SYSCALL_CAPABILITY_WORKER },
    { 76U, "sys.worker.error", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING, AIVM_SYSCALL_CAPABILITY_WORKER },
    { 77U, "sys.worker.cancel", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL, AIVM_SYSCALL_CAPABILITY_WORKER },
    { 78U, "sys.debug.emit", 2U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_DEBUG },
    { 79U, "sys.debug.mode", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING, AIVM_SYSCALL_CAPABILITY_DEBUG },
    { 80U, "sys.debug.captureFrameBegin", 3U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_DEBUG },
    { 81U, "sys.debug.captureFrameEnd", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_DEBUG },
    { 82U, "sys.debug.captureDraw", 2U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_DEBUG },
    { 83U, "sys.debug.captureInput", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_DEBUG },
    { 84U, "sys.debug.captureState", 2U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_DEBUG },
    { 85U, "sys.debug.replayLoad", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT, AIVM_SYSCALL_CAPABILITY_DEBUG },
    { 86U, "sys.debug.replayNext", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING, AIVM_SYSCALL_CAPABILITY_DEBUG },
    { 87U, "sys.debug.assert", 3U, { AIVM_VAL_BOOL, AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_DEBUG },
    { 88U, "sys.debug.artifactWrite", 2U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL, AIVM_SYSCALL_CAPABILITY_DEBUG },
    { 89U, "sys.debug.traceAsync", 3U, { AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID, AIVM_SYSCALL_CAPABILITY_DEBUG },
    { 115U, "sys.debug.taskReclaimStats", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_NODE, AIVM_SYSCALL_CAPABILITY_DEBUG }
};

static AivmContractStatus validate_contract(
    const AivmSyscallContract* contract,
    const AivmValue* args,
    size_t arg_count,
    AivmValueType* out_return_type)
{
    size_t arg_index;

    if (out_return_type != NULL) {
        *out_return_type = AIVM_VAL_VOID;
    }

    if (contract == NULL) {
        return AIVM_CONTRACT_ERR_UNKNOWN_TARGET;
    }

    if (contract->arg_count != arg_count) {
        return AIVM_CONTRACT_ERR_ARG_COUNT;
    }

    for (arg_index = 0U; arg_index < arg_count; arg_index += 1U) {
        if (args == NULL || args[arg_index].type != contract->arg_types[arg_index]) {
            return AIVM_CONTRACT_ERR_ARG_TYPE;
        }
    }

    if (out_return_type != NULL) {
        *out_return_type = contract->return_type;
    }
    return AIVM_CONTRACT_OK;
}

const AivmSyscallContract* aivm_syscall_contract_find_by_target(const char* target)
{
    size_t index;

    if (target == NULL) {
        return NULL;
    }

    for (index = 0U; index < (sizeof(Contracts) / sizeof(Contracts[0])); index += 1U) {
        if (strcmp(Contracts[index].target, target) == 0) {
            return &Contracts[index];
        }
    }

    return NULL;
}

const AivmSyscallContract* aivm_syscall_contract_find_by_id(uint32_t id)
{
    size_t index;
    for (index = 0U; index < (sizeof(Contracts) / sizeof(Contracts[0])); index += 1U) {
        if (Contracts[index].id == id) {
            return &Contracts[index];
        }
    }
    return NULL;
}

AivmSyscallCapabilityGroup aivm_syscall_contract_capability(const char* target)
{
    const AivmSyscallContract* contract = aivm_syscall_contract_find_by_target(target);
    if (contract == NULL) {
        return AIVM_SYSCALL_CAPABILITY_NONE;
    }
    return contract->capability;
}

const char* aivm_syscall_capability_name(AivmSyscallCapabilityGroup capability)
{
    switch (capability) {
        case AIVM_SYSCALL_CAPABILITY_NONE:
            return "none";
        case AIVM_SYSCALL_CAPABILITY_CORE:
            return "core";
        case AIVM_SYSCALL_CAPABILITY_CONSOLE:
            return "console";
        case AIVM_SYSCALL_CAPABILITY_PROCESS:
            return "process";
        case AIVM_SYSCALL_CAPABILITY_PLATFORM:
            return "platform";
        case AIVM_SYSCALL_CAPABILITY_TIME:
            return "time";
        case AIVM_SYSCALL_CAPABILITY_FILESYSTEM:
            return "filesystem";
        case AIVM_SYSCALL_CAPABILITY_CRYPTO:
            return "crypto";
        case AIVM_SYSCALL_CAPABILITY_NETWORK:
            return "network";
        case AIVM_SYSCALL_CAPABILITY_UI:
            return "ui";
        case AIVM_SYSCALL_CAPABILITY_WORKER:
            return "worker";
        case AIVM_SYSCALL_CAPABILITY_REMOTE:
            return "remote";
        case AIVM_SYSCALL_CAPABILITY_HOST:
            return "host";
        case AIVM_SYSCALL_CAPABILITY_IMAGE:
            return "image";
        case AIVM_SYSCALL_CAPABILITY_DEBUG:
            return "debug";
        default:
            return "unknown";
    }
}

int aivm_syscall_capability_from_name(
    const char* name,
    AivmSyscallCapabilityGroup* out_capability)
{
    AivmSyscallCapabilityGroup capability;
    if (name == NULL || out_capability == NULL) {
        return 0;
    }
    for (capability = AIVM_SYSCALL_CAPABILITY_CORE;
         capability <= AIVM_SYSCALL_CAPABILITY_DEBUG;
         capability = (AivmSyscallCapabilityGroup)(capability + 1)) {
        if (strcmp(name, aivm_syscall_capability_name(capability)) == 0) {
            *out_capability = capability;
            return 1;
        }
    }
    return 0;
}

int aivm_syscall_contract_is_debug_target(const char* target)
{
    return aivm_syscall_contract_capability(target) == AIVM_SYSCALL_CAPABILITY_DEBUG;
}

int aivm_syscall_contract_should_bind_in_production(const char* target)
{
    AivmSyscallCapabilityGroup capability = aivm_syscall_contract_capability(target);
    return capability != AIVM_SYSCALL_CAPABILITY_NONE &&
           capability != AIVM_SYSCALL_CAPABILITY_DEBUG;
}

AivmContractStatus aivm_syscall_contract_validate(
    const char* target,
    const AivmValue* args,
    size_t arg_count,
    AivmValueType* out_return_type)
{
    const AivmSyscallContract* contract = aivm_syscall_contract_find_by_target(target);
    if (contract == NULL) {
        return AIVM_CONTRACT_ERR_UNKNOWN_TARGET;
    }
    return validate_contract(contract, args, arg_count, out_return_type);
}

AivmContractStatus aivm_syscall_contract_validate_id(
    uint32_t id,
    const AivmValue* args,
    size_t arg_count,
    AivmValueType* out_return_type)
{
    const AivmSyscallContract* contract = aivm_syscall_contract_find_by_id(id);
    if (contract == NULL) {
        if (out_return_type != NULL) {
            *out_return_type = AIVM_VAL_VOID;
        }
        return AIVM_CONTRACT_ERR_UNKNOWN_ID;
    }
    return validate_contract(contract, args, arg_count, out_return_type);
}

const char* aivm_contract_status_code(AivmContractStatus status)
{
    switch (status) {
        case AIVM_CONTRACT_OK:
            return "AIVMC000";
        case AIVM_CONTRACT_ERR_UNKNOWN_TARGET:
            return "AIVMC001";
        case AIVM_CONTRACT_ERR_ARG_COUNT:
            return "AIVMC002";
        case AIVM_CONTRACT_ERR_ARG_TYPE:
            return "AIVMC003";
        case AIVM_CONTRACT_ERR_UNKNOWN_ID:
            return "AIVMC004";
        default:
            return "AIVMC999";
    }
}

const char* aivm_contract_status_message(AivmContractStatus status)
{
    switch (status) {
        case AIVM_CONTRACT_OK:
            return "Syscall contract validation passed.";
        case AIVM_CONTRACT_ERR_UNKNOWN_TARGET:
            return "Syscall target was not found.";
        case AIVM_CONTRACT_ERR_ARG_COUNT:
            return "Syscall argument count was invalid.";
        case AIVM_CONTRACT_ERR_ARG_TYPE:
            return "Syscall argument type was invalid.";
        case AIVM_CONTRACT_ERR_UNKNOWN_ID:
            return "Syscall contract ID was not found.";
        default:
            return "Unknown syscall contract validation status.";
    }
}
